[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
ndarray = "0.16.1"
nom = { version = "7.1.3", features = ["alloc"] }
nom-supreme = "0.8.0"
peg = "0.8.4"
rayon = "1.10.0"
regex = "1.11.1"
